export const CART_ADD_ITEM="CART_ADD_ITEM";
export const CART_REMOVE_ITEM="CART_REMOVE_ITEM";
export const CART_SHIPPING_DETAILS="CART_SHIPPING_DETAILS";
export const CART_PAYMENT_METHOD="CART_PAYMENT_METHOD";
export const CART_EMPTY="CART_EMPTY";
